Repository nubank/fklearn, pull requests merged in 2019-07, with the labels that each got.

#82 Remove useless requirement
  requirements.txt
Labels: bug

#79 Make `customer_transformer` a pure function
  .gitignore
  src/fklearn/training/transformation.py
  tests/training/test_transformation.py
Labels: bug

#81 Add shap multiclass support
  src/fklearn/training/classification.py
  tests/training/test_classification.py
Labels: enhancement

#77 adding custom model to pipeline (issue #70)
  src/fklearn/training/regression.py
  tests/training/test_regression.py
Labels: enhancement, review-request

#85 Remove unused requirement
  requirements.txt
Labels: enhancement, review-request
