Repository nubank/fklearn, pull requests merged in 2019-10, with the labels that each got.

#98 Fix/split evaluator extractor key error
  src/fklearn/metrics/pd_extractors.py
  tests/metrics/test_pd_extractors.py
Labels: bug, ready-to-merge

#101 Adding PR AUC evaluator
  .gitignore
  docs/source/api.rst
  docs/source/examples/causal_inference.ipynb
  docs/source/examples/learning_curves.rst
  src/fklearn/tuning/parameter_tuners.py
  src/fklearn/validation/evaluators.py
  tests/__init__.py
  tests/tuning/test_parameter_tuners.py
  tests/tuning/test_samplers.py
  tests/tuning/test_selectors.py
  tests/tuning/test_stoppers.py
  tests/tuning/test_utils.py
  tests/validation/test_evaluators.py
Labels: enhancement, review-request

#104 Bump version
  CHANGELOG.md
  src/fklearn/resources/VERSION
Labels: review-request

#102 Make it possible to have a gap between training and holdout in time splitters
  src/fklearn/preprocessing/splitting.py
  tests/preprocessing/test_splitting.py
Labels: review-request

#103 Modify code style raising errors rather using asserts to check corrections
  src/fklearn/training/pipeline.py
  src/fklearn/training/regression.py
  src/fklearn/training/transformation.py
  src/fklearn/validation/evaluators.py
  src/fklearn/validation/splitters.py
  tests/training/test_pipeline.py
Labels: ready-to-merge
