Repository nubank/fklearn, pull requests merged in 2019-05, with the labels that each got.

#52 Add catboosting classifier
  src/fklearn/training/classification.py
  tests/training/test_classification.py
Labels: enhancement, ready-to-merge

#74 Fix upper bound of requirements
  requirements.txt
Labels: bug, review-request

#73 Fix upper bound of requirements
  requirements.txt
Labels: bug, review-request

#72 Fix upper bound of requirements
  requirements.txt
Labels: bug, review-request

#65 Add extractor for temporal split evaluator
  src/fklearn/metrics/pd_extractors.py
  tests/metrics/test_pd_extractors.py
Labels: ready-to-merge

#64 Minor fix in flake8 documentation command to make it work on other shells
  docs/source/contributing.rst
Labels: ready-to-merge

#71 Changing the nan column to not include the first one dropped
  src/fklearn/training/transformation.py
Labels: bug, review-request

#67 Correct score name in fbeta_score_evaluator docstring
  src/fklearn/validation/evaluators.py
Labels: documentation, review-request
