Repository nubank/fklearn, pull requests merged in 2019-06, with the labels that each got.

#76 Typo on learner_doc_string of onehot_categorizer function - issue #75
  src/fklearn/training/transformation.py
Labels: bug, documentation, ready-to-merge

#58 Fix issue with encoded columns in pipeline
  src/fklearn/training/classification.py
  src/fklearn/training/regression.py
  src/fklearn/training/transformation.py
  src/fklearn/training/unsupervised.py
  src/fklearn/training/utils.py
  tests/training/test_pipeline.py
  tests/training/test_transformation.py
  tests/training/test_utils.py
Labels: enhancement, ready-to-merge

#66 Tutorial
  docs/source/examples/fklearn_overview.ipynb
  docs/source/examples/fklearn_overview_dataset_generation.ipynb
  docs/source/examples/index.rst
  notebooks/imgs/EvalFn.png
  notebooks/imgs/Extractor.png
  notebooks/imgs/LearningCurves.png
  notebooks/imgs/Pipeline.png
  notebooks/imgs/SpatialLearningCurves.png
  notebooks/imgs/Splitting_Data.png
Labels: review-request
