Repository nubank/fklearn, pull requests merged in 2019-04, with the labels that each got.

#31 Fixed some documentation in splitters.py
  src/fklearn/validation/splitters.py
Labels: documentation

#35 Update docs
  .circleci/config.yml
  README.md
  docs/source/api.rst
  docs/source/conf.py
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/pages/introduction.rst
  scripts/build_docs.sh
  src/fklearn/__init__.py
  src/fklearn/training/classification.py
Labels: documentation

#36 Add code coverage tests
  .codecov.yml
  .coveragerc
  README.md
  requirements_test.txt
  scripts/run_tests.sh
Labels: enhancement

#38 Fix docs warnings
  docs/source/getting_started.rst
  docs/source/index.rst
  src/fklearn/preprocessing/splitting.py
  src/fklearn/training/classification.py
  src/fklearn/training/ensemble.py
  src/fklearn/training/regression.py
  src/fklearn/training/transformation.py
  src/fklearn/tuning/parameter_tuners.py
  src/fklearn/tuning/stoppers.py
  src/fklearn/validation/evaluators.py
  src/fklearn/validation/splitters.py
  src/fklearn/validation/validator.py
Labels: documentation

#39 Add link to blog post
  docs/source/getting_started.rst
Labels: documentation

#41 Update copyright info
  LICENSE
Labels: documentation

#43 Update sklearn imputer
  src/fklearn/training/imputation.py
Labels: bug

#40 Add examples section to documentation
  .circleci/config.yml
  docs/requirements.txt
  docs/source/conf.py
  docs/source/examples/causal_inference.ipynb
  docs/source/examples/index.rst
  docs/source/examples/nlp_classification.rst
  docs/source/examples/regression.ipynb
  docs/source/index.rst
Labels: documentation

#42 Adding Examples section to documentation, and learning curves example
  docs/source/examples/index.rst
  docs/source/examples/learning_curves.rst
Labels: documentation

#48 Bump version to 1.13.3
  CHANGELOG.md
  src/fklearn/resources/VERSION
Labels: others

#47 Fix notebook link on getting_started.rst
  docs/source/getting_started.rst
Labels: documentation

#50 Update learning_curves.rst
  docs/source/examples/learning_curves.rst
Labels: documentation

#30 First iteration of a data corruption feature
  notebooks/chaos-demo.ipynb
  src/fklearn/types/types.py
  src/fklearn/validation/perturbators.py
  src/fklearn/validation/validator.py
  tests/validation/test_perturbators.py
  tests/validation/test_validator.py
Labels: enhancement, ready-to-merge

#45 Add CatBoosting regressor
  notebooks/catboost_demo.ipynb
  requirements.txt
  src/fklearn/training/regression.py
  tests/training/test_regression.py
Labels: enhancement, ready-to-merge

#49 validator accepts predict_oof as argument
  CHANGELOG.md
  src/fklearn/resources/VERSION
  src/fklearn/validation/validator.py
Labels: enhancement, ready-to-merge

#54 Fix indentation in document.
  docs/source/getting_started.rst
Labels: documentation, ready-to-merge

#46 Git clone simplified and parentheses removed
  docs/source/getting_started.rst
Labels: documentation, ready-to-merge

#59 Contribution guide
  .github/CODEOWNERS
  .github/pull_request_template.md
  Brewfile
  CONTRIBUTING.md
  README.md
  docs/source/contributing.rst
  docs/source/index.rst
Labels: documentation, review-request

#57 Fixing imports in regression example notebook. (#55)
  docs/source/examples/regression.ipynb
Labels: documentation, ready-to-merge
